# coding: utf-8

"""
    HrConnect

    JWT token is required for authorization. Access to the API is granted through Simployer Admin Center: https://admincenter.simployer.com/    Endpoints with pagination support return following headers      x-has-next-page: True (indicates whether there are more records)      x-page: 1 (page numeration starts with 1)      x-page-size: 100 (records per page)      x-total-count: 120 (total number of records)      x-total-pages: 2 (total number of pages)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from simployer_client.api.employments_api import EmploymentsApi


class TestEmploymentsApi(unittest.TestCase):
    """EmploymentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EmploymentsApi()

    def tearDown(self) -> None:
        pass

    def test_v1_employments_contracts_get(self) -> None:
        """Test case for v1_employments_contracts_get

        Retrieves contracts with pagination.
        """
        pass

    def test_v1_employments_contracts_id_get(self) -> None:
        """Test case for v1_employments_contracts_id_get

        Retrieves the contract with given identifier.
        """
        pass

    def test_v1_employments_contracts_person_id_get(self) -> None:
        """Test case for v1_employments_contracts_person_id_get

        Retrieves the contracts associated with person.
        """
        pass

    def test_v1_employments_employee_id_get(self) -> None:
        """Test case for v1_employments_employee_id_get

        Retrieves employments for given employee.
        """
        pass

    def test_v1_employments_get(self) -> None:
        """Test case for v1_employments_get

        Retrieves employments with pagination.
        """
        pass

    def test_v1_employments_id_get(self) -> None:
        """Test case for v1_employments_id_get

        Retrieves employments with given identifier.
        """
        pass

    def test_v1_employments_person_id_get(self) -> None:
        """Test case for v1_employments_person_id_get

        Retrieves employments for given person.
        """
        pass

    def test_v1_employments_salaries_employment_id_get(self) -> None:
        """Test case for v1_employments_salaries_employment_id_get

        Retrieves salary for given employment.
        """
        pass

    def test_v1_employments_salaries_get(self) -> None:
        """Test case for v1_employments_salaries_get

        Retrieves salaries with pagination.
        """
        pass

    def test_v1_employments_salaries_person_id_get(self) -> None:
        """Test case for v1_employments_salaries_person_id_get

        Retrieves salaries for given person.
        """
        pass

    def test_v1_employments_termination_causes_get(self) -> None:
        """Test case for v1_employments_termination_causes_get

        Retrieves termination causes with pagination.
        """
        pass

    def test_v1_employments_termination_causes_id_get(self) -> None:
        """Test case for v1_employments_termination_causes_id_get

        Retrieves termination cause with given identifier.
        """
        pass


if __name__ == '__main__':
    unittest.main()
