# coding: utf-8

"""
    HrConnect

    JWT token is required for authorization. Access to the API is granted through Simployer Admin Center: https://admincenter.simployer.com/    Endpoints with pagination support return following headers      x-has-next-page: True (indicates whether there are more records)      x-page: 1 (page numeration starts with 1)      x-page-size: 100 (records per page)      x-total-count: 120 (total number of records)      x-total-pages: 2 (total number of pages)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from simployer_client.models.organization_hierarchy import OrganizationHierarchy

class TestOrganizationHierarchy(unittest.TestCase):
    """OrganizationHierarchy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrganizationHierarchy:
        """Test OrganizationHierarchy
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrganizationHierarchy`
        """
        model = OrganizationHierarchy()
        if include_optional:
            return OrganizationHierarchy(
                id = '',
                sub_type = 'Enterprise',
                name = '',
                company_number = '',
                active = True,
                department_code = '',
                manager_id = '',
                parent_organization_id = '',
                organization_number = '',
                nace = '',
                system_country = 'Afghanistan',
                system_organization_currency = 'SEK',
                sub_organizations = [
                    simployer_client.models.organization_hierarchy.OrganizationHierarchy(
                        id = '', 
                        sub_type = 'Enterprise', 
                        name = '', 
                        company_number = '', 
                        active = True, 
                        department_code = '', 
                        manager_id = '', 
                        parent_organization_id = '', 
                        organization_number = '', 
                        nace = '', 
                        system_country = 'Afghanistan', 
                        system_organization_currency = 'SEK', 
                        sub_organizations = [
                            simployer_client.models.organization_hierarchy.OrganizationHierarchy(
                                id = '', 
                                name = '', 
                                company_number = '', 
                                active = True, 
                                department_code = '', 
                                manager_id = '', 
                                parent_organization_id = '', 
                                organization_number = '', 
                                nace = '', )
                            ], )
                    ]
            )
        else:
            return OrganizationHierarchy(
        )
        """

    def testOrganizationHierarchy(self):
        """Test OrganizationHierarchy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
