# coding: utf-8

"""
    HrConnect

    JWT token is required for authorization. Access to the API is granted through Simployer Admin Center: https://admincenter.simployer.com/    Endpoints with pagination support return following headers      x-has-next-page: True (indicates whether there are more records)      x-page: 1 (page numeration starts with 1)      x-page-size: 100 (records per page)      x-total-count: 120 (total number of records)      x-total-pages: 2 (total number of pages)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from simployer_client.api.persons_api import PersonsApi


class TestPersonsApi(unittest.TestCase):
    """PersonsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PersonsApi()

    def tearDown(self) -> None:
        pass

    def test_v1_persons_children_get(self) -> None:
        """Test case for v1_persons_children_get

        Retrieves children.
        """
        pass

    def test_v1_persons_children_id_get(self) -> None:
        """Test case for v1_persons_children_id_get

        Retrieves child.
        """
        pass

    def test_v1_persons_extended_properties_get(self) -> None:
        """Test case for v1_persons_extended_properties_get

        Retrieves extended properties.
        """
        pass

    def test_v1_persons_extended_properties_id_get(self) -> None:
        """Test case for v1_persons_extended_properties_id_get

        Retrieves extended property with given value identifier.
        """
        pass

    def test_v1_persons_extended_properties_type_id_get(self) -> None:
        """Test case for v1_persons_extended_properties_type_id_get

        Retrieves extended properties with given type identifier.
        """
        pass

    def test_v1_persons_get(self) -> None:
        """Test case for v1_persons_get

        Retrieves a paginated list of people.
        """
        pass

    def test_v1_persons_id_children_get(self) -> None:
        """Test case for v1_persons_id_children_get

        Retrieves children for person.
        """
        pass

    def test_v1_persons_id_extended_properties_get(self) -> None:
        """Test case for v1_persons_id_extended_properties_get

        Retrieves extended properties for person.
        """
        pass

    def test_v1_persons_id_get(self) -> None:
        """Test case for v1_persons_id_get

        Retrieves person with given identifier.
        """
        pass

    def test_v1_persons_id_identity_identifiers_get(self) -> None:
        """Test case for v1_persons_id_identity_identifiers_get

        Retrieves identity identifiers for given person.
        """
        pass

    def test_v1_persons_id_next_of_kin_get(self) -> None:
        """Test case for v1_persons_id_next_of_kin_get

        Retrieves next of kin for person.
        """
        pass

    def test_v1_persons_identity_identifiers_get(self) -> None:
        """Test case for v1_persons_identity_identifiers_get

        Retrieves identity identifiers.
        """
        pass

    def test_v1_persons_identity_identifiers_id_get(self) -> None:
        """Test case for v1_persons_identity_identifiers_id_get

        Retrieves identity identifiers with given identifier.
        """
        pass

    def test_v1_persons_manager_structure_get(self) -> None:
        """Test case for v1_persons_manager_structure_get

        Retrieves the manager structure.
        """
        pass

    def test_v1_persons_next_of_kin_get(self) -> None:
        """Test case for v1_persons_next_of_kin_get

        Retrieves next of kin.
        """
        pass

    def test_v1_persons_next_of_kin_id_get(self) -> None:
        """Test case for v1_persons_next_of_kin_id_get

        Retrieves next of kin.
        """
        pass


if __name__ == '__main__':
    unittest.main()
