# coding: utf-8

"""
    HrConnect

    JWT token is required for authorization. Access to the API is granted through Simployer Admin Center: https://admincenter.simployer.com/    Endpoints with pagination support return following headers      x-has-next-page: True (indicates whether there are more records)      x-page: 1 (page numeration starts with 1)      x-page-size: 100 (records per page)      x-total-count: 120 (total number of records)      x-total-pages: 2 (total number of pages)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from simployer_client.api.contacts_api import ContactsApi


class TestContactsApi(unittest.TestCase):
    """ContactsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ContactsApi()

    def tearDown(self) -> None:
        pass

    def test_v1_contacts_addresses_get(self) -> None:
        """Test case for v1_contacts_addresses_get

        Retrieves addresses with pagination.
        """
        pass

    def test_v1_contacts_addresses_id_get(self) -> None:
        """Test case for v1_contacts_addresses_id_get

        Retrieves address with given identifier.
        """
        pass

    def test_v1_contacts_addresses_unit_id_get(self) -> None:
        """Test case for v1_contacts_addresses_unit_id_get

        Retrieves addresses for unit.
        """
        pass

    def test_v1_contacts_electronic_addresses_get(self) -> None:
        """Test case for v1_contacts_electronic_addresses_get

        Retrieves electronic addresses with pagination.
        """
        pass

    def test_v1_contacts_electronic_addresses_id_get(self) -> None:
        """Test case for v1_contacts_electronic_addresses_id_get

        Retrieves electronic address with given identifier.
        """
        pass

    def test_v1_contacts_electronic_addresses_unit_id_get(self) -> None:
        """Test case for v1_contacts_electronic_addresses_unit_id_get

        Retrieves electronic addresses for unit.
        """
        pass

    def test_v1_contacts_phone_numbers_get(self) -> None:
        """Test case for v1_contacts_phone_numbers_get

        Retrieves phone numbers with pagination.
        """
        pass

    def test_v1_contacts_phone_numbers_id_get(self) -> None:
        """Test case for v1_contacts_phone_numbers_id_get

        Retrieves phone number with given identifier.
        """
        pass

    def test_v1_contacts_phone_numbers_unit_id_get(self) -> None:
        """Test case for v1_contacts_phone_numbers_unit_id_get

        Retrieves phone numbers for unit.
        """
        pass


if __name__ == '__main__':
    unittest.main()
