# coding: utf-8

# flake8: noqa

"""
    HrConnect

    JWT token is required for authorization. Access to the API is granted through Simployer Admin Center: https://admincenter.simployer.com/    Endpoints with pagination support return following headers      x-has-next-page: True (indicates whether there are more records)      x-page: 1 (page numeration starts with 1)      x-page-size: 100 (records per page)      x-total-count: 120 (total number of records)      x-total-pages: 2 (total number of pages)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from simployer_client.api.contacts_api import ContactsApi
from simployer_client.api.employees_api import EmployeesApi
from simployer_client.api.employments_api import EmploymentsApi
from simployer_client.api.organizations_api import OrganizationsApi
from simployer_client.api.persons_api import PersonsApi
from simployer_client.api.tenants_api import TenantsApi

# import ApiClient
from simployer_client.api_response import ApiResponse
from simployer_client.api_client import ApiClient
from simployer_client.configuration import Configuration
from simployer_client.exceptions import OpenApiException
from simployer_client.exceptions import ApiTypeError
from simployer_client.exceptions import ApiValueError
from simployer_client.exceptions import ApiKeyError
from simployer_client.exceptions import ApiAttributeError
from simployer_client.exceptions import ApiException

# import models into sdk package
from simployer_client.models.address import Address
from simployer_client.models.address_type import AddressType
from simployer_client.models.agreement_status import AgreementStatus
from simployer_client.models.assignment_unit_type import AssignmentUnitType
from simployer_client.models.child import Child
from simployer_client.models.contract import Contract
from simployer_client.models.contract_type import ContractType
from simployer_client.models.country_type import CountryType
from simployer_client.models.electronic_address import ElectronicAddress
from simployer_client.models.electronic_address_type import ElectronicAddressType
from simployer_client.models.employee import Employee
from simployer_client.models.employment import Employment
from simployer_client.models.extended_property import ExtendedProperty
from simployer_client.models.extended_property_pagination import ExtendedPropertyPagination
from simployer_client.models.group import Group
from simployer_client.models.group_category import GroupCategory
from simployer_client.models.group_manager import GroupManager
from simployer_client.models.group_people_relations import GroupPeopleRelations
from simployer_client.models.hour_unit import HourUnit
from simployer_client.models.identity_identifier import IdentityIdentifier
from simployer_client.models.next_of_kin import NextOfKin
from simployer_client.models.organization import Organization
from simployer_client.models.organization_currency_type import OrganizationCurrencyType
from simployer_client.models.organization_hierarchy import OrganizationHierarchy
from simployer_client.models.organization_unit_type import OrganizationUnitType
from simployer_client.models.period_type import PeriodType
from simployer_client.models.person import Person
from simployer_client.models.person_identity_identifier_type import PersonIdentityIdentifierType
from simployer_client.models.person_manager_relationship import PersonManagerRelationship
from simployer_client.models.phone import Phone
from simployer_client.models.phone_type import PhoneType
from simployer_client.models.salary import Salary
from simployer_client.models.salary_currency_type import SalaryCurrencyType
from simployer_client.models.sex_type import SexType
from simployer_client.models.signature_type_enum import SignatureTypeEnum
from simployer_client.models.tenant import Tenant
from simployer_client.models.termination_cause import TerminationCause
from simployer_client.models.unit_type import UnitType
