# coding: utf-8

"""
    HrConnect

    JWT token is required for authorization. Access to the API is granted through Simployer Admin Center: https://admincenter.simployer.com/    Endpoints with pagination support return following headers      x-has-next-page: True (indicates whether there are more records)      x-page: 1 (page numeration starts with 1)      x-page-size: 100 (records per page)      x-total-count: 120 (total number of records)      x-total-pages: 2 (total number of pages)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class PersonManagerRelationship(BaseModel):
    """
    Represents the relationship between a person and their manager.
    """ # noqa: E501
    person_name: Optional[StrictStr] = Field(default=None, description="Name of the person.", alias="personName")
    person_id: Optional[StrictStr] = Field(default=None, description="Identifier of the person.", alias="personId")
    manager_name: Optional[StrictStr] = Field(default=None, description="Name of the manager.", alias="managerName")
    manager_id: Optional[StrictStr] = Field(default=None, description="Identifier of the manager.", alias="managerId")
    is_specified_manager: Optional[StrictBool] = Field(default=None, description="Indicates if the manager is specified.", alias="isSpecifiedManager")
    last_changed: Optional[datetime] = Field(default=None, description="Date when the relationship was last changed.", alias="lastChanged")
    __properties: ClassVar[List[str]] = ["personName", "personId", "managerName", "managerId", "isSpecifiedManager", "lastChanged"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PersonManagerRelationship from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "person_id",
            "manager_id",
            "is_specified_manager",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if person_name (nullable) is None
        # and model_fields_set contains the field
        if self.person_name is None and "person_name" in self.model_fields_set:
            _dict['personName'] = None

        # set to None if manager_name (nullable) is None
        # and model_fields_set contains the field
        if self.manager_name is None and "manager_name" in self.model_fields_set:
            _dict['managerName'] = None

        # set to None if manager_id (nullable) is None
        # and model_fields_set contains the field
        if self.manager_id is None and "manager_id" in self.model_fields_set:
            _dict['managerId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PersonManagerRelationship from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "personName": obj.get("personName"),
            "personId": obj.get("personId"),
            "managerName": obj.get("managerName"),
            "managerId": obj.get("managerId"),
            "isSpecifiedManager": obj.get("isSpecifiedManager"),
            "lastChanged": obj.get("lastChanged")
        })
        return _obj


